name: Ubuntu

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  ubuntu1804:
    runs-on: ubuntu-18.04

    env:
      OPENSSL_VERSION: 1.1.1
      OPENSSL_PKG_NAME: openssl-1.1.1k.tar.gz
      OPENSSL_DIR_NAME: openssl-1.1.1k
      PKG_NAME: openssl-1.1.1k-ubuntu

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 下载openssl源码
      - name: download openssl
        run: |
          wget https://openssl.org/source/old/${{ env.OPENSSL_VERSION }}/${{ env.OPENSSL_PKG_NAME }} -O ${{ env.OPENSSL_PKG_NAME }}
          tar xzf ${{ env.OPENSSL_PKG_NAME }}

      # 编译
      - name: build
        run: |
          cp build_ubuntu_openssl.sh ${{ env.OPENSSL_DIR_NAME }}
          cd ${{ env.OPENSSL_DIR_NAME }}
          chmod a+x build_ubuntu_openssl.sh && ./build_ubuntu_openssl.sh

      # 压缩
      - name: 7zip libs
        run: |
          cp -r ${{ env.OPENSSL_DIR_NAME }}/build/openssl ${{ env.PKG_NAME }}
          7z a ${{ env.PKG_NAME }}.7z ${{ env.PKG_NAME }}
          rm ${{ env.PKG_NAME }} -r -fo

      # 上传
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_NAME }}.7z