name: Windows

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  windows-vs2019:
    runs-on: windows-2019

    env:
      OPENSSL_VERSION: 1.1.1
      OPENSSL_PKG_NAME: openssl-1.1.1k.tar.gz
      OPENSSL_DIR_NAME: openssl-1.1.1k

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 下载openssl源码
      - name: download openssl
        run: |
          Invoke-WebRequest -Uri https://openssl.org/source/old/${{ env.OPENSSL_VERSION }}/${{ env.OPENSSL_PKG_NAME }} -OutFile ${{ env.OPENSSL_PKG_NAME }}
          tar xzf ${{ env.OPENSSL_PKG_NAME }}
      
      # 编译
      - name: build
        run: |
          cp build_windows_openssl.bat ${{ env.OPENSSL_DIR_NAME }}
          cd ${{ env.OPENSSL_DIR_NAME }}
          ./build_windows_openssl.bat